### PR TITLE
update package.json

### PR DESCRIPTION
**Pull request by Ross146**
all working fine in react 16

### CODE REVIEW

**Comment by jerridan** [comment]
Is there something blocking this merge? Anything that can be done to help it along?

**Comment by nicholasserra** [comment]
@jerridan Just seeing your comment. Will give it a run early next week, thanks.

**Comment by hector** [comment]
It works good for me in React 16, seems like there is no incompatibility.

**Comment by nicholasserra** [comment]
Version 2.4.3 released. Let me know if anyone sees any issues, thanks!

**Comment by hector** [comment]
I am using react@16.2.0 and I am still receiving the warning:
```
warning " > react-loader@2.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ~16.0.0".
warning " > react-loader@2.4.3" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ~16.0.0".
```

**Comment by nicholasserra** [comment]
You said "still", were you seeing this before?

**Comment by hector** [comment]
After `yarn install`:
```
warning " > react-loader@2.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ~16.0.0".
warning " > react-loader@2.4.3" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ~16.0.0".
```

This happens because I am using react version 16.2.0.
**You need to change the peer dependencies string from ~16.0.0 to ^16.0.0.**

Check the documentation:
https://docs.npmjs.com/getting-started/semantic-versioning

**Pull request merged**
