### PR TITLE
Removed React 15.5 warnings

### PR DESCRIPTION
**Pull request by ramusus**
Added `prop-types`, `create-react-class` package dependencies, updated component to use prop-types lib instead of `React.PropType` and create-react-class instead of `React.createClass`

Here is more info about warnings https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

### CODE REVIEW

**Comment by gfx** [comment]
+1

**Comment by joelfsreis** [comment]
+1

**Comment by ramusus** [comment]
Any chance to get it merged?

**Comment by marcgarreau** [comment]
looks good to me! thanks for the patch.

**Comment by joelfsreis** [comment]
thanks @marcgarreau

**Pull request merged**
